# Generated by Django 5.0.6 on 2024-05-15 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('приложение_стажировка', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeDateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='приложение_стажировка.user')),
            ],
        ),
    ]
