# Generated by Django 5.0.6 on 2024-05-15 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('приложение_стажировка', '0004_alter_freedatetime_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freedatetime',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='приложение_стажировка.user'),
        ),
    ]
